//@version=4
//Created by user ChrisMoody updated 4-10-2014
//Regular MACD Indicator with Histogram that plots 4 Colors Based on Direction Above and Below the Zero Line
//Update allows Check Box Options, Show MacD & Signal Line, Show Change In color of MacD Line based on cross of Signal Line.
//Show Dots at Cross of MacD and Signal Line, Histogram can show 4 colors or 1, Turn on and off Histogram.
//Special Thanks to that incredible person in Tech Support whoem I won't say you r name so you don't get bombarded with emails
//Note the feature Tech Support showed me on how to set the default timeframe of the indicator to the chart Timeframe, but also allow you to choose a different timeframe.
//By the way I fully disclose that I completely STOLE the Dots at the MAcd Cross from "TheLark"

study(title="CM_MacD_Ult_MTF", shorttitle="CM_Ult_MacD_MTF")
source = close
useCurrentRes = input(true, title="Use Current Chart Resolution?")
resCustom = input(title="Use Different Timeframe? Uncheck Box Above", type=input.resolution, defval="60")
smd = input(true, title="Show MacD & Signal Line? Also Turn Off Dots Below")
sd = input(true, title="Show Dots When MacD Crosses Signal Line?")
sh = input(true, title="Show Histogram?")
macd_colorChange = input(true,title="Change MacD Line Color-Signal Line Cross?")
hist_colorChange = input(true,title="MacD Histogram 4 Colors?")

res = useCurrentRes ? timeframe.period : resCustom

fastLength = input(12, minval=1), slowLength=input(26,minval=1)
signalLength=input(9,minval=1)

fastMA = ema(source, fastLength)
slowMA = ema(source, slowLength)

macd = fastMA - slowMA
signal = sma(macd, signalLength)
hist = macd - signal

outMacD = security(syminfo.tickerid, res, macd)
outSignal = security(syminfo.tickerid, res, signal)
outHist = security(syminfo.tickerid, res, hist)

histA_IsUp = outHist > outHist[1] and outHist > 0
histA_IsDown = outHist < outHist[1] and outHist > 0
histB_IsDown = outHist < outHist[1] and outHist <= 0
histB_IsUp = outHist > outHist[1] and outHist <= 0


//MacD Color Definitions
macd_IsAbove = outMacD >= outSignal
macd_IsBelow = outMacD < outSignal


plot_color = hist_colorChange ? histA_IsUp ? color.aqua : histA_IsDown ? color.blue : histB_IsDown ? color.red : histB_IsUp ? color.maroon :color.yellow : color.gray
macd_color = macd_colorChange ? macd_IsAbove ? color.lime : color.red : color.red
signal_color = macd_colorChange ? macd_IsAbove ? color.orange : color.orange : color.navy



circleYPosition = outSignal

plot(smd and outMacD ? outMacD : na, title="MACD", color=macd_color, linewidth=2)
plot(smd and outSignal ? outSignal : na, title="Signal Line", color=signal_color, style=plot.style_line ,linewidth=2)
plot(sh and outHist ? outHist : na, title="Histogram", color=plot_color, style=plot.style_histogram, linewidth=2)
plot(sd and cross(outMacD, outSignal) ? circleYPosition : na, title="Cross", style=plot.style_circles, linewidth=2, color=macd_color)
hline(0, '0 Line', linestyle=hline.style_solid, linewidth=2, color=color.gray)

/////

fastMA2 = hma(source, fastLength)
slowMA2 = hma(source, slowLength)

macd2 = fastMA2 - slowMA2
signal2 = sma(macd2, signalLength)
hist2 = macd2 - signal2

outMacD2 = security(syminfo.tickerid, res, macd2)
outSignal2 = security(syminfo.tickerid, res, signal2)
outHist2 = security(syminfo.tickerid, res, hist2)


histA_IsUp2 = outHist2 > outHist2[1] and outHist2 > 0
histA_IsDown2 = outHist2 < outHist2[1] and outHist2 > 0
histB_IsDown2 = outHist2 < outHist2[1] and outHist2 <= 0
histB_IsUp2 = outHist2 > outHist2[1] and outHist2 <= 0


macd_IsAbove2 = outMacD2 >= outSignal2
macd_IsBelow2 = outMacD2 < outSignal2

plot_color2 = hist_colorChange ? histA_IsUp2 ? color.green : histA_IsDown2 ? color.purple : histB_IsDown2 ? color.purple : histB_IsUp2 ? color.maroon :color.yellow :color.gray
macd_color2 = macd_colorChange ? macd_IsAbove2 ? color.lime : color.red : color.red
signal_color2 = macd_colorChange ? macd_IsAbove2 ? color.orange : color.orange : color.navy


circleYPosition2 = outSignal2



plot(smd and outMacD2 ? outMacD2 : na, title="MACD", color=macd_color2, linewidth=1)
plot(smd and outSignal2 ? outSignal2 : na, title="Signal Line", color=signal_color2, style=plot.style_line ,linewidth=1)
plot(sh and outHist2 ? outHist2 : na, title="Histogram", color=plot_color2, style=plot.style_histogram, linewidth=1)
plot(sd and cross(outMacD2, outSignal2) ? circleYPosition2 : na, title="Cross", style=plot.style_circles, linewidth=1, color=macd_color2)
//hline(0, '0 Line', linestyle=solid, linewidth=2, color=gray)

